# Generated by Django 3.2.9 on 2022-03-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220316_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='News/'),
        ),
        migrations.AddField(
            model_name='news',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='News/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img1',
            field=models.ImageField(default=1, upload_to='News/'),
            preserve_default=False,
        ),
    ]
